### ISSUE TITLE
TODO: Compute mass redistribution in one catchment

### ISSUE THREAD

**Issue by jkingslake** [jkingslake/BFRN_meltwater#2]
Initially ignore the flow of water from one catchment to another by overtopping

**Comment by jkingslake** [comment]
- [ ] Use the lake locations from WAIS in [this](https://essd.copernicus.org/articles/14/209/2022/) paper and EAIS in [this](https://www.nature.com/articles/s41598-019-50343-5) paper. 
start by downloading the WAIS ones from here: https://zenodo.org/record/5642755#.Y4ohhezMIeU)
- [ ] for one lake (and eventually all of them) compute the lowest point
- [ ] use this lowest point as the our point for a catchment calculation using [pysheds](https://github.com/mdbartos/pysheds) (or similar)
- [ ] assume all water in the lake (as estimated by the lake volumes in the papers above, using scaling) came from the catchment and was evenly distributed across the catchment. 
- [ ] calculate the depth of the lake by evenly distributing the lake's volume over its area
- [ ] create a raster which is the lake depths minus the catchment melt
- [ ] multiple this raster by the BFRN raster
